str1='akhil sabu sabu'
print(str1.capitalize())
print(str1.lower())
print(str1.swapcase())
print(str1.title())
print(str1.upper())

print(str1.count('a'))
print(str1.endswith('l'))
print(str1.endswith('i'))
print(str1.startswith('a'))
print(str1.startswith('k'))
print(str1.find('sabu'))
print(str1.rfind('sabu'))
print(str1.index('a'))
print(str1.rindex('a'))

print(str1.isalnum())
print(str1.isalpha())
print(str1.isascii())
print(str1.isdigit())
print(str1.isidentifier())
print(str1.islower())
print(str1.isupper())
print(str1.iskeyword())